Name:		texlive-custom-bib
Version:	4.32
Release:	1
Summary:	Customised BibTeX styles
Group:		Publishing
URL:		http://www.ctan.org/tex-archive/macros/latex/contrib/custom-bib
License:	LPPL
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/custom-bib.tar.xz
Source1:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/custom-bib.doc.tar.xz
Source2:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/custom-bib.source.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(post):	texlive-tlpkg
Conflicts:	texlive-texmf <= 20110705-3
Conflicts:	texlive-doc <= 20110705-3
Conflicts:	texlive-source <= 20110705-3

%description
Package generating customized BibTeX bibliography styles from a
generic file using docstrip driven by parameters generated by a
menu application. Includes support for the Harvard style of
citations.

%pre
    %_texmf_mktexlsr_pre

%post
    %_texmf_mktexlsr_post

%preun
    if [ $1 -eq 0 ]; then
	%_texmf_mktexlsr_pre
    fi

%postun
    if [ $1 -eq 0 ]; then
	%_texmf_mktexlsr_post
    fi

#-----------------------------------------------------------------------
%files
%{_texmfdistdir}/tex/latex/custom-bib/catalan.mbs
%{_texmfdistdir}/tex/latex/custom-bib/dansk.mbs
%{_texmfdistdir}/tex/latex/custom-bib/dutch.mbs
%{_texmfdistdir}/tex/latex/custom-bib/english.mbs
%{_texmfdistdir}/tex/latex/custom-bib/esperant.mbs
%{_texmfdistdir}/tex/latex/custom-bib/finnish.mbs
%{_texmfdistdir}/tex/latex/custom-bib/french.mbs
%{_texmfdistdir}/tex/latex/custom-bib/geojour.mbs
%{_texmfdistdir}/tex/latex/custom-bib/geophys.tex
%{_texmfdistdir}/tex/latex/custom-bib/german.mbs
%{_texmfdistdir}/tex/latex/custom-bib/italian.mbs
%{_texmfdistdir}/tex/latex/custom-bib/makebst.tex
%{_texmfdistdir}/tex/latex/custom-bib/merlin.mbs
%{_texmfdistdir}/tex/latex/custom-bib/norsk.mbs
%{_texmfdistdir}/tex/latex/custom-bib/photjour.mbs
%{_texmfdistdir}/tex/latex/custom-bib/physjour.mbs
%{_texmfdistdir}/tex/latex/custom-bib/polski.mbs
%{_texmfdistdir}/tex/latex/custom-bib/portuges.mbs
%{_texmfdistdir}/tex/latex/custom-bib/shorthnd.tex
%{_texmfdistdir}/tex/latex/custom-bib/slovene.mbs
%{_texmfdistdir}/tex/latex/custom-bib/spanish.mbs
%{_texmfdistdir}/tex/latex/custom-bib/suppjour.mbs
%{_texmfdistdir}/tex/latex/custom-bib/svenska.mbs
%doc %{_texmfdistdir}/doc/latex/custom-bib/README.V432
%doc %{_texmfdistdir}/doc/latex/custom-bib/makebst.pdf
%doc %{_texmfdistdir}/doc/latex/custom-bib/merlin.pdf
#- source
%doc %{_texmfdistdir}/source/latex/custom-bib/makebst.drv
%doc %{_texmfdistdir}/source/latex/custom-bib/makebst.dtx
%doc %{_texmfdistdir}/source/latex/custom-bib/makebst.ins
%doc %{_texmfdistdir}/source/latex/custom-bib/shorthnd.ins

#-----------------------------------------------------------------------
%prep
%setup -c -a0 -a1 -a2

%build

%install
mkdir -p %{buildroot}%{_texmfdistdir}
cp -fpar tex doc source %{buildroot}%{_texmfdistdir}
